### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [CadisRaziel/finance_app_flutter#1]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/CadisRaziel-finance_app_flutter

**Comment by CadisRaziel** [comment]
I appreciate that I compiled it on the web, but the idea is only mobile for now, even so thanks for testing on the web!
